### ISSUE TITLE
Peristent error after linting invalid code

### ISSUE THREAD

**Issue by ravicious** [venantius/vim-eastwood#3]
So basically if I add an extra paren and save the file I get the following error. After fixing it and saving the file, I get the same error over and over again; I have to restart vim for it to disappear.

```
Error detected while processing function <SNR>47_BufWritePostHook..<SNR>47_UpdateErrors..<SNR>47_CacheErrors..37..36..SyntaxCheckers_clojure_eastwood_GetLocList:
line    5:
E121: Undefined variable: l:cljfmt_output
Error detected while processing function <SNR>47_BufWritePostHook..<SNR>47_UpdateErrors..<SNR>47_CacheErrors:
line   34:
E170: Missing :endfor
Error detected while processing function <SNR>47_BufWritePostHook..<SNR>47_UpdateErrors:
line   13:
E171: Missing :endif
```

I use both vim-eastwood and vim-cljfmt on mvim. My `~/.lein/profiles.clj` looks like this:

``` clojure
{:user {:plugins [[cider/cider-nrepl "0.8.2"]
                  [lein-cljfmt "0.1.7"]
                  [jonase/eastwood "0.2.1"]
                  ]
        :dependencies [
                       [lein-cljfmt "0.1.7"]
                       [jonase/eastwood "0.2.1"]
                       ]}}
```

Moreover, Syntastic doesn't show eastwood warnings, even though it's enabled (I've checked with `:SyntasticInfo`). But that's another issue and I'd like to try to fix this one first.

**Comment by venantius** [comment]
This seems to be a cljfmt error, not an eastwood error. Mind opening a bug there?

**Comment by venantius** [comment]
*vim-cljfmt, that is

**Comment by ravicious** [comment]
Yeah, sure. I was thinking about it, but then decided to post it here as there's "eastwood" in the first line.

Closing and opening it there in a sec.

**Comment by venantius** [comment]
Yeah, this is a weird one. I think the two are interacting with each other somehow; one's triggering the other.

**Comment by venantius** [comment]
Going to leave this issue open as well for the moment.
