### ISSUE TITLE
Errors when reloading vimrc

### ISSUE THREAD

**Issue by h35514n** [venantius/vim-eastwood#6]
Error detected while processing ~/vim/plugins/vim-eastwood/plugin/eastwood.vim:

```
line   19:
E122: Function EastwoodRequire already exists, add ! to replace it
line   27:
E122: Function EastwoodCallback already exists, add ! to replace it
line   37:
E122: Function EastwoodLintNS already exists, add ! to replace it
```

**Comment by venantius** [comment]
This suggests to me that somehow you have multiple copies of the plugin installed, or you've got something going on that's loading everything more than once. There is a patch I could do that would suppress the error you're getting, but the fact that you're getting it suggests that there's some weird import behavior going on that may be more of an issue.

**Comment by h35514n** [comment]
Ah sorry, I should have added that this occurs when I source my `.vimrc`. I think most plugins use `function!` to allow for reloading your vim config without the error.

**Comment by venantius** [comment]
Ah, right; just pushed up 20050f04f8dc65d171d9b5b1bac78c36a38af518 which should resolve this.

**Comment by h35514n** [comment]
:+1: Thanks!  :)
