### ISSUE TITLE
"No matching autocommands" message in statusline

### ISSUE THREAD

**Issue by bradJM** [venantius/vim-eastwood#8]
Screenshot's attached. Everything is working fine (errors are being checked and reported when present, sending code over to Fireplace to be evaluated also works), but "No matching autocommands" is always present in the statusline where the line number of an error should be. It also appears at the top of the loclist. It appears in both places whether there are any errors in the current file or not. Running MacVim 7.4.979, downloaded from their repository.

![screenshot 2015-12-30 10 18 12](https://cloud.githubusercontent.com/assets/1667870/12055124/fbb8c16a-aede-11e5-9002-c70690e8f0d7.png)

Not sure if it's relevant, but my profiles.clj looks like this:

``` clojure
{:user {:plugins [[venantius/ultra "0.4.0"]
                  [jonase/eastwood "0.2.3"]]
        :dependencies [[jonase/eastwood "0.2.3" :exclusions [org.clojure/clojure]]]
        :ultra {:color-scheme :solarized_dark}}}
{:repl {:plugins [[cider/cider-nrepl "0.10.0"]]
        :dependencies [[org.clojure/tools.nrepl "0.2.12"]]}}
```

Here's my .vimrc:

```
execute pathogen#infect()
syntax on
filetype plugin indent on

set ignorecase
set smartcase
set hlsearch

colorscheme solarized
set background=dark
set guifont=Sauce\ Code\ Powerline:h12
set guioptions-=r

autocmd BufEnter * sign define dummy
autocmd BufEnter * execute 'sign place 9999 line=1 name=dummy buffer=' . bufnr('')
highlight clear SignColumn

set splitbelow
set splitright

set tabstop=2
set shiftwidth=2
set expandtab

let mapleader=" "

nnoremap <leader><leader> <c-^>
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l
nnoremap <Left> :echoe "Use h"<CR>
nnoremap <Right> :echoe "Use l"<CR>
nnoremap <Up> :echoe "Use k"<CR>
nnoremap <Down> :echoe "Use j"<CR>

let g:airline_powerline_fonts=1
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_javascript_checkers=['eslint']
```

And my plugins, managed with Pathogen:

```
syntastic            vim-colors-solarized vim-fireplace
vim-airline          vim-eastwood         vim-sensible
```

Thanks!

**Comment by venantius** [comment]
I'll try to take a look at this at some point this upcoming weekend. I was experiencing some issues of my own with this and it's possible they're related.

**Comment by nirrub** [comment]
Any update on this? - facing the exact same issue and was wondering if you have any leads.
Thanks!

**Comment by venantius** [comment]
I don't have an update yet, sorry - my current job doesn't afford me the opportunity to write Clojure professionally so I only run up against new bugs these days when I'm tinkering on hobby projects.

**Comment by nirrub** [comment]
I managed to resolve this issue. I made a couple of changes so I don't know which one solved it:
1. Installed Tim Pope's salve with all its dependencies - vim-projectionist and vim-dispatch (https://github.com/tpope/vim-salve)
2. Updated Syntastic and Fireplace

Restarted everything - Error gone.

**Comment by venantius** [comment]
@bradJM mind giving @nirrub's solutions a shot and seeing if they resolve the issue? If so, let us know what works!

**Comment by bradJM** [comment]
Installing vim-salve (and dependencies) did the trick. Thanks for the tip, @nirrub!

**Comment by venantius** [comment]
Closing.

**Comment by danielbraun** [comment]
Installing vim-salve and it dependencies worked.
